// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAo2_q6J0zaKZdhgqGbPPprVDPi6I1TLA',
    appId: '1:926361378609:web:78b5e96eee41f50ebfda10',
    messagingSenderId: '926361378609',
    projectId: 'paxtechandroid',
    authDomain: 'paxtechandroid.firebaseapp.com',
    storageBucket: 'paxtechandroid.firebasestorage.app',
    measurementId: 'G-TVX1C6X8QK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwoSxit3B1cH_YvOOdFXeBn3rxqK8xyXU',
    appId: '1:926361378609:android:89ad0df94b9d2275bfda10',
    messagingSenderId: '926361378609',
    projectId: 'paxtechandroid',
    storageBucket: 'paxtechandroid.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu2aTfMfxOEUTYyEiBD0RxjXl0TQT046I',
    appId: '1:926361378609:ios:c41780c909a1f01dbfda10',
    messagingSenderId: '926361378609',
    projectId: 'paxtechandroid',
    storageBucket: 'paxtechandroid.firebasestorage.app',
    iosBundleId: 'com.example.iosmobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu2aTfMfxOEUTYyEiBD0RxjXl0TQT046I',
    appId: '1:926361378609:ios:c41780c909a1f01dbfda10',
    messagingSenderId: '926361378609',
    projectId: 'paxtechandroid',
    storageBucket: 'paxtechandroid.firebasestorage.app',
    iosBundleId: 'com.example.iosmobileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAo2_q6J0zaKZdhgqGbPPprVDPi6I1TLA',
    appId: '1:926361378609:web:ddc6f3f987f66a29bfda10',
    messagingSenderId: '926361378609',
    projectId: 'paxtechandroid',
    authDomain: 'paxtechandroid.firebaseapp.com',
    storageBucket: 'paxtechandroid.firebasestorage.app',
    measurementId: 'G-C90N7XBDE8',
  );

}